version: "3.9"

services:
  custom:
    build:
      context: .
      dockerfile: ./docker/custom.Dockerfile
    container_name: custom
    init: true
    ports:
      - 8092:3000
    volumes:
      - .:/root/.config/nvim
    stdin_open: true
    tty: true
    command: /bin/bash

  lazynvim:
    build:
      context: .
      dockerfile: ./docker/lazynvim.Dockerfile
    container_name: lazynvim
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash
