version: "3.9"

services:
  hello:
    build: .
    container_name: nvim-config
    init: true
    ports:
      - 8092:3000
    volumes:
      - .:/root/.config/nvim
    stdin_open: true
    tty: true
    command: /bin/bash
