local saga = require('lspsaga')
local icons = require('modules.ui.icons')

saga.setup({
   ui = {
      theme = 'round',
      border = 'rounded',
      title = true,
      winblend = 0,
      expand = '',
      collapse = '',
      preview = ' ',
      code_action = 'ﯧ ',
      diagnostic = 'ﯧ ',
      incoming = ' ',
      outgoing = ' ',
      colors = {
         --float window normal bakcground color
         normal_bg = '#1d1536',
         --title background color
         title_bg = '#afd700',
      },
      kind = {
         -- Class = { icons.kind.Class .. ' ', colors.yellow },
         -- Constant = { icons.kind.Constant .. ' ', colors.peach },
         -- Constructor = { icons.kind.Constructor .. ' ', colors.sapphire },
         -- Enum = { icons.kind.Enum .. ' ', colors.yellow },
         -- EnumMember = { icons.kind.EnumMember .. ' ', colors.teal },
         -- Event = { icons.kind.Event .. ' ', colors.yellow },
         -- Field = { icons.kind.Field .. ' ', colors.teal },
         -- File = { icons.kind.File .. ' ', colors.rosewater },
         -- Function = { icons.kind.Function .. ' ', colors.blue },
         -- Interface = { icons.kind.Interface .. ' ', colors.yellow },
         -- Key = { icons.kind.Keyword .. ' ', colors.red },
         -- Method = { icons.kind.Method .. ' ', colors.blue },
         -- Module = { icons.kind.Module .. ' ', colors.blue },
         -- Namespace = { icons.kind.Namespace .. ' ', colors.blue },
         -- Number = { icons.kind.Number .. ' ', colors.peach },
         -- Operator = { icons.kind.Operator .. ' ', colors.sky },
         -- Package = { icons.kind.Package .. ' ', colors.blue },
         -- Property = { icons.kind.Property .. ' ', colors.teal },
         -- Struct = { icons.kind.Struct .. ' ', colors.yellow },
         -- TypeParameter = { icons.kind.TypeParameter .. ' ', colors.maroon },
         -- Variable = { icons.kind.Variable .. ' ', colors.peach },
         -- -- Type
         -- Array = { icons.type.Array .. ' ', colors.peach },
         -- Boolean = { icons.type.Boolean .. ' ', colors.peach },
         -- Null = { icons.type.Null .. ' ', colors.yellow },
         -- Object = { icons.type.Object .. ' ', colors.yellow },
         -- String = { icons.type.String .. ' ', colors.green },
         -- -- ccls-specific iconss .. " ".
         -- TypeAlias = { icons.kind.TypeAlias .. ' ', colors.green },
         -- Parameter = { icons.kind.Parameter .. ' ', colors.blue },
         -- StaticMethod = { icons.kind.StaticMethod .. ' ', colors.peach },
      },
   },
   diagnostic = {
      show_code_action = true,
      show_source = true,
      jump_num_shortcut = true,
      keys = {
         exec_action = 'o',
         quit = 'q',
         go_action = 'g',
      },
   },
   code_action = {
      num_shortcut = true,
      keys = {
         quit = 'q',
         exec = '<CR>',
      },
   },
   lightbulb = {
      enable = true,
      enable_in_insert = true,
      cache_code_action = false,
      sign = true,
      sign_priority = 40,
      virtual_text = false,
   },
   preview = {
      lines_above = 0,
      lines_below = 20,
   },
   scroll_preview = {
      scroll_down = '<C-p>',
      scroll_up = '<C-n>',
   },
   request_timeout = 2000,
   finder = {
      edit = { 'o', '<CR>' },
      vsplit = 's',
      split = 'i',
      tabe = 't',
      quit = { 'q', '<ESC>' },
   },
   definition = {
      edit = '<C-c>o',
      vsplit = '<C-c>v',
      split = '<C-c>i',
      tabe = '<C-c>t',
      quit = 'q',
      close = '<Esc>',
   },
   rename = {
      quit = '<C-c>',
      exec = '<CR>',
      mark = 'x',
      confirm = '<CR>',
      in_select = true,
   },
   symbol_in_winbar = {
      enable = true,
      separator = '  ',
      hide_keyword = true,
      show_file = true,
      folder_level = 2,
      respect_root = false,
      color_mode = true,
   },
   outline = {
      win_position = 'right',
      win_with = '',
      win_width = 30,
      show_detail = true,
      auto_preview = true,
      auto_refresh = true,
      auto_close = true,
      custom_sort = nil,
      keys = {
         jump = 'o',
         expand_collapse = 'u',
         quit = 'q',
      },
   },
   callhierarchy = {
      show_detail = false,
      keys = {
         edit = 'e',
         vsplit = 's',
         split = 'i',
         tabe = 't',
         jump = 'o',
         quit = 'q',
         expand_collapse = 'u',
      },
   },
   server_filetype_map = {},
})
