local M = {}

M.opts = {
   preset = 'modern',
   plugins = { spelling = true },
   icons = {
      breadcrumb = '»',
      separator = '➜',
      group = '+',
   },
   keys = {
      scroll_down = '<C-d>',
      scroll_up = '<C-u>',
   },
   win = {
      border = 'rounded',
      -- position = 'bottom',
   },
   -- defaults = {
   --    mode = { 'n', 'v' },
   --    ['g'] = { name = '+goto' },
   --    ['gz'] = { name = '+surround' },
   --    ['gc'] = { name = '+comment' },
   --    [']'] = { name = '+next' },
   --    ['['] = { name = '+prev' },
   --    ['<leader><tab>'] = { name = '+tabs' },
   --    ['<leader>b'] = { name = '+buffer' },
   --    -- ['<leader>c'] = { name = '+code' },
   --    ['<leader>f'] = { name = '+file/find' },
   --    ['<leader>g'] = { name = '+git' },
   --    ['<leader>gc'] = { name = '+checkout' },
   --    ['<leader>gd'] = { name = '+diff' },
   --    ['<leader>gh'] = { name = '+hunks' },
   --    ['<leader>gr'] = { name = '+reset' },
   --    ['<leader>gs'] = { name = '+stage' },
   --    ['<leader>gt'] = { name = '+toggle' },
   --    ['<leader>gw'] = { name = '+worktrees' },
   --    ['<leader>h'] = { name = '+harpoon' },
   --    ['<leader>i'] = { name = '+icons' },
   --    ['<leader>q'] = { name = '+quit/session' },
   --    ['<leader>j'] = { name = '+split/join' },
   --    ['<leader>l'] = { name = '+lsp' },
   --    ['<leader>la'] = { name = '+actions' },
   --    ['<leader>ls'] = { name = '+show' },
   --    ['<leader>m'] = { name = '+mini-map' },
   --    ['<leader>n'] = { name = '+nvim-tree' },
   --    ['<leader>s'] = { name = '+search' },
   --    ['<leader>sn'] = { name = '+noice' },
   --    ['<leader>S'] = { name = '+search/replace' },
   --    ['<leader>t'] = { name = '+terminal' },
   --    ['<leader>w'] = { name = '+windows' },
   --    ['<leader>x'] = { name = '+diagnostics/quickfix' },
   --    ['<leader>;'] = { name = '+snippets' },
   -- },
}

M.config = function(_, opts)
   local wk = require('which-key')
   wk.setup(opts)
   wk.add({
      {
         mode = { 'n', 'v' },
         { '<leader>;', group = 'snippets' },
         { '<leader><tab>', group = 'tabs' },
         { '<leader>S', group = 'search/replace' },
         { '<leader>b', group = 'buffer' },
         { '<leader>f', group = 'file/find' },
         { '<leader>g', group = 'git' },
         { '<leader>gc', group = 'checkout' },
         { '<leader>gd', group = 'diff' },
         { '<leader>gh', group = 'hunks' },
         { '<leader>gr', group = 'reset' },
         { '<leader>gs', group = 'stage' },
         { '<leader>gt', group = 'toggle' },
         { '<leader>gw', group = 'worktrees' },
         { '<leader>h', group = 'harpoon' },
         { '<leader>i', group = 'icons' },
         { '<leader>j', group = 'split/join' },
         { '<leader>l', group = 'lsp' },
         { '<leader>la', group = 'actions' },
         { '<leader>ls', group = 'show' },
         { '<leader>m', group = 'mini-map' },
         { '<leader>n', group = 'nvim-tree' },
         { '<leader>q', group = 'quit/session' },
         { '<leader>s', group = 'search' },
         { '<leader>sn', group = 'noice' },
         { '<leader>t', group = 'terminal' },
         { '<leader>w', group = 'windows' },
         { '<leader>x', group = 'diagnostics/quickfix' },
         { '[', group = 'prev' },
         { ']', group = 'next' },
         { 'g', group = 'goto' },
         { 'gc', group = 'comment' },
         { 'gz', group = 'surround' },
      },
   })
   -- wk.register(opts.defaults)
end

return M
