name: lint+test

on:
  push:
    branches: ["lazy"]
  pull_request:
    branches: ["lazy"]

jobs:
  lint-lua:
    name: Lint Neovim Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .

      - name: Lint
        uses: lunarmodules/luacheck@v1
        with:
          args: init.lua lua/
