name: tree-sitter

on:
  push:
    branches: ["lazy"]
  pull_request:
    branches: ["lazy"]

jobs:
  compile:
    name: Compile Parsers
    # if: startsWith(github.event.head_commit.message, 'chore(release)') || startsWith(github.event.head_commit.message, 'ci(treesitter)')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            "x86_64-windows",
            "x86_64-linux",
            "aarch64-linux",
            "x86_64-macos",
            "aarch64-macos",
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: "scripts/requirements.txt"

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.9.1

      - name: Set pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install script deps
        shell: bash
        run: |
          sudo apt install jq
          pip3 install -r scripts/requirements.txt
          pnpm add -g tree-sitter-cli

      - name: Setup Neovim
        shell: bash
        run: |
          bash ./scripts/reset.sh && rm -rf ~/.config/nvim
          mkdir -p ~/.config/nvim && cp -r ./* ~/.config/nvim
          nvim --headless -c 'Lazy restore' -c 'q'

      - name: Compile Parsers
        shell: bash
        run: |
          python3 ./scripts/compile-ts-parsers.py

      - name: Archive Parsers (Linux + Mac)
        if: ${{ matrix.target != 'x86_64-windows' }}
        shell: bash
        run: |
          name="treesitter-${{ matrix.target }}"
          mv "/tmp/${name}" ./treesitter
          tar -cvf "${name}.tar" ./treesitter
          cat "${name}.tar" | gzip --best > "${name}.tar.gz"
          rm -r ./treesitter "${name}.tar"

      - name: Archive Parsers (Windows)
        if: ${{ matrix.target == 'x86_64-windows' }}
        shell: bash
        run: |
          name="treesitter-${{ matrix.target }}"
          mv "/tmp/${name}" ./treesitter
          7z a "${name}.zip" ./treesitter
          rm -r ./treesitter

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: treesitter-${{ matrix.target }}
          path: |
            *.tar.gz
            *.zip

      - name: Set Release Name
        id: set_release
        run: |
          commit_hash=$(jq -r '."nvim-treesitter".commit' .\lazy-lock.personal.json)
          echo "name=$commit_hash" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.tar.gz
            *.zip
          name: ${{ steps.set_release.outputs.name }}
          generate_release_notes: true
