name: tree-sitter

on:
  push:
    branches: ["lazy"]
  pull_request:
    branches: ["lazy"]

jobs:
  compile:
    name: Tree-Sitter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.9.1

      - name: print pwd
        shell: bash
        run: |
          pwd
          ls -la
          which nvim && nvim -v
